In [3]:
import torch as torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**Random Tensor**
NN always begin with random tensors, then keep adjusting themselves till they reach the optimum representation

In [4]:
randomTensor = torch.rand(3,4)

In [5]:
randomTensor.ndim

2

In [6]:
randomTensor.shape

torch.Size([3, 4])

This tensor have 3 list with 4 numbers inside of it. Dimension 0 is 3 objects. and Dimension 1 is 4 objects.

In [7]:
randomTensor1 = torch.rand(2,3,4,5)
randomTensor1

tensor([[[[0.9098, 0.8292, 0.0818, 0.3624, 0.8537],
          [0.3432, 0.9405, 0.8128, 0.9212, 0.5426],
          [0.9384, 0.9029, 0.2563, 0.7989, 0.9504],
          [0.0922, 0.7090, 0.1661, 0.7916, 0.9053]],

         [[0.5646, 0.7130, 0.8428, 0.7806, 0.9169],
          [0.6344, 0.7571, 0.7782, 0.6573, 0.7835],
          [0.5914, 0.2041, 0.2275, 0.8277, 0.8097],
          [0.8093, 0.4464, 0.1467, 0.8734, 0.8135]],

         [[0.4438, 0.5923, 0.4497, 0.1780, 0.7267],
          [0.2509, 0.8918, 0.3901, 0.0485, 0.2329],
          [0.4867, 0.2003, 0.3644, 0.7080, 0.0341],
          [0.7759, 0.3593, 0.8123, 0.6525, 0.6376]]],


        [[[0.7078, 0.8052, 0.5428, 0.1835, 0.6688],
          [0.5119, 0.9030, 0.5148, 0.4378, 0.2753],
          [0.5789, 0.0859, 0.5450, 0.6889, 0.6356],
          [0.9127, 0.0257, 0.2939, 0.9190, 0.5298]],

         [[0.2421, 0.6100, 0.5152, 0.1443, 0.7019],
          [0.4517, 0.5967, 0.9197, 0.7029, 0.1322],
          [0.8736, 0.6974, 0.7505, 0.3262, 0.1826],
  

**Zeros and Ones Tensor:** This is used to mask something. Filters our desired object/image out of the provided image.

In [8]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

**Range of Tensors:**

In [10]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [12]:
tensor_dtypes = torch.tensor([3.0,6.0,9.0], dtype=torch.float32)
tensor_dtypes.dtype

torch.float32

tensor datatype usually have 3 kinds of error.
1. Tensor doesn't have identical dtypes
2. Tensor doesn have identical shape
3. Tensor doesn't have right device

***Manupliation***
Reshaping, Stacking, Squeezing and Unsqueezing
* Reshaping- changes shape of tensor
* View - shows a different shape of our input tensor
* Stack - Stack tensor vertically and horizontally (vstack and hstack)
* Squeeze- Removes one dimension
* Unsqeeze - add one dimension
* Permute - Return vieew of tensor with dimension permuted (swapped) in a certain way.

In [13]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

New dimensions should always be compatable with the old dimenions.
* Rule of Thumb is the answer of multiplication of all new dimensions should be equal to number of elements in old tensor

In [16]:
x.reshape(1,3,3)

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

View() is  same as reshape but, it shares same memory. It works like pointer. It will simply point towards x when we call z. Any changes to z will create change to x automatically.

In [23]:
z = x.view(9,1)
z, z.shape

(tensor([[50.],
         [50.],
         [50.],
         [50.],
         [50.],
         [50.],
         [50.],
         [50.],
         [50.]]),
 torch.Size([9, 1]))

In [32]:
z.view(9,1)
x

tensor([50., 50., 50., 50., 50., 50., 50., 50., 50.])

STACKING

In [49]:
x = torch.arange(1,100.,10.)
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[ 1.,  1.,  1.,  1.],
        [11., 11., 11., 11.],
        [21., 21., 21., 21.],
        [31., 31., 31., 31.],
        [41., 41., 41., 41.],
        [51., 51., 51., 51.],
        [61., 61., 61., 61.],
        [71., 71., 71., 71.],
        [81., 81., 81., 81.],
        [91., 91., 91., 91.]])

Squeezing simply removes any dimenion with size of 1. (Basically redundent useless backet/dimension)

In [56]:
x_reshaped = x.reshape(1,1,10)
x_reshaped

tensor([[[ 1., 11., 21., 31., 41., 51., 61., 71., 81., 91.]]])

In [57]:
squeezed = torch.squeeze(x)
squeezed

tensor([ 1., 11., 21., 31., 41., 51., 61., 71., 81., 91.])

Unsqueeezing add an additional dimenion inside of a tensor. Idk how to use it rn

In [65]:
y = torch.unsqueeze(squeezed, dim = 0)

Permute: Changes the dimenions order. Basically elements are arranged in different order in arrays underneath.

In [68]:
y.permute(1,0)

tensor([[ 1.],
        [11.],
        [21.],
        [31.],
        [41.],
        [51.],
        [61.],
        [71.],
        [81.],
        [91.]])

**INDEXING**

In [83]:
x = torch.arange(1,100).reshape(1,1,33,3)
x

tensor([[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9],
          [10, 11, 12],
          [13, 14, 15],
          [16, 17, 18],
          [19, 20, 21],
          [22, 23, 24],
          [25, 26, 27],
          [28, 29, 30],
          [31, 32, 33],
          [34, 35, 36],
          [37, 38, 39],
          [40, 41, 42],
          [43, 44, 45],
          [46, 47, 48],
          [49, 50, 51],
          [52, 53, 54],
          [55, 56, 57],
          [58, 59, 60],
          [61, 62, 63],
          [64, 65, 66],
          [67, 68, 69],
          [70, 71, 72],
          [73, 74, 75],
          [76, 77, 78],
          [79, 80, 81],
          [82, 83, 84],
          [85, 86, 87],
          [88, 89, 90],
          [91, 92, 93],
          [94, 95, 96],
          [97, 98, 99]]]])

In [90]:
x[:,:,1,:]

tensor([[[4, 5, 6]]])

You can query the index as much as the number of number of dimension. If dimensions are 4, You can query indexing with only 4 dimensions

**NUMPY AND PYTORCH**

In [93]:
import torch as torch
import numpy as np

In [92]:
random = np.arange(1,10)
random_tensor = torch.from_numpy(random)
random, random_tensor

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

Reproducibility
* Note: When you use comparison operator with tensors. It compares every value of tensor with corresponding value.

In [1]:
!nvidia-smi

Thu Nov 14 07:14:03 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   54C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--