In [ ]:
import torch as torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**Random Tensor**
NN always begin with random tensors, then keep adjusting themselves till they reach the optimum representation

In [ ]:
randomTensor = torch.rand(3,4)

In [ ]:
randomTensor.ndim

2

In [ ]:
randomTensor.shape

torch.Size([3, 4])

This tensor have 3 list with 4 numbers inside of it. Dimension 0 is 3 objects. and Dimension 1 is 4 objects.

In [ ]:
randomTensor1 = torch.rand(2,3,4,5)
randomTensor1

tensor([[[[0.1465, 0.8157, 0.0184, 0.5360, 0.4733],
          [0.6686, 0.7272, 0.9423, 0.3896, 0.0704],
          [0.1842, 0.2493, 0.0681, 0.1728, 0.9750],
          [0.7173, 0.3209, 0.6945, 0.1161, 0.8399]],

         [[0.7836, 0.3966, 0.4916, 0.2399, 0.2127],
          [0.8740, 0.5269, 0.0294, 0.0295, 0.5957],
          [0.8967, 0.6871, 0.0538, 0.0349, 0.0516],
          [0.5576, 0.4757, 0.2829, 0.5632, 0.3623]],

         [[0.2646, 0.9679, 0.0599, 0.4473, 0.3404],
          [0.3786, 0.5971, 0.1242, 0.7024, 0.0375],
          [0.2279, 0.6645, 0.9044, 0.3652, 0.5044],
          [0.1113, 0.1642, 0.2171, 0.0718, 0.5249]]],


        [[[0.0268, 0.4815, 0.2284, 0.6163, 0.2159],
          [0.2536, 0.2087, 0.0423, 0.9784, 0.3531],
          [0.1508, 0.8369, 0.1863, 0.2067, 0.0335],
          [0.1401, 0.9630, 0.7143, 0.2519, 0.9630]],

         [[0.4978, 0.8048, 0.2663, 0.6505, 0.8085],
          [0.4872, 0.6936, 0.6971, 0.4296, 0.4670],
          [0.1678, 0.7130, 0.0414, 0.9916, 0.6434],
  

**Zeros and Ones Tensor:** This is used to mask something. Filters our desired object/image out of the provided image.

In [ ]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

**Range of Tensors:**

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [ ]:
tensor_dtypes = torch.tensor([3.0,6.0,9.0], dtype=torch.float32)
tensor_dtypes.dtype

torch.float32

tensor datatype usually have 3 kinds of error.
1. Tensor doesn't have identical dtypes
2. Tensor doesn have identical shape
3. Tensor doesn't have right device

In [16]:
!git init



Reinitialized existing Git repository in /content/.git/


In [18]:
!git remote add origin git@github.com:Ali-Haider006/Pytorch.git

error: remote origin already exists.


In [24]:
!git add .


In [25]:
!git commit -m 'Tensor and operation'  # commit in Colab
!git push

[master (root-commit) 3c3eb38] Tensor and operation
 21 files changed, 50994 insertions(+)
 create mode 100644 .config/.last_opt_in_prompt.yaml
 create mode 100644 .config/.last_survey_prompt.yaml
 create mode 100644 .config/.last_update_check.json
 create mode 100644 .config/active_config
 create mode 100644 .config/config_sentinel
 create mode 100644 .config/configurations/config_default
 create mode 100644 .config/default_configs.db
 create mode 100644 .config/gce
 create mode 100644 .config/hidden_gcloud_config_universe_descriptor_data_cache_configs.db
 create mode 100644 .config/logs/2024.11.11/14.20.33.654791.log
 create mode 100644 .config/logs/2024.11.11/14.20.55.167301.log
 create mode 100644 .config/logs/2024.11.11/14.21.08.086797.log
 create mode 100644 .config/logs/2024.11.11/14.21.09.214033.log
 create mode 100644 .config/logs/2024.11.11/14.21.22.150373.log
 create mode 100644 .config/logs/2024.11.11/14.21.22.879217.log
 create mode 100755 sample_data/README.md
 create mod

In [20]:
!git config --global user.email "ah0062527@gmail.com"
!git config --global user.name "Ali Haider"